### ISSUE TITLE
Using Request with a relative url doesn't work

### ISSUE THREAD

**Issue by nathanhannig** [mswjs/jest-fixed-jsdom#23]
I noticed in testing a project that uses a relative path instead of an absolute path when creating a Request
```
new Request('/relative/path', {
  body: JSON.stringify(data),
}
```

A type error is thrown
```
TypeError: Failed to parse URL from /relative/path
Cause:
TypeError: Invalid URL
```

I believe the browser implementation of Request allows relative path because it can determine the base url, while the node version of Request does not.

**Comment by kettanaito** [comment]
How does this behave in HappyDOM? Node's `Request` won't support relative URLs because there's nothing to be relative to in Node.

**Comment by nathanhannig** [comment]
hmm, switching to "@happy-dom/jest-environment", I am using MSW (node) with my project and am hitting a issue

```
    ReferenceError: BroadcastChannel is not defined

    > 1 | import { http, HttpResponse } from "msw";
          | ^      
```
